### ISSUE TITLE
app/Providers/RouteServiceProvider.php Route Bind Problem

### ISSUE THREAD

**Issue by ahmadronaghdev** [engrnvd/laravel-crud-generator#12]
Could not add route model binding for the route 'app-user'.
Please add the following line manually in /Applications/MAMP/htdocs/laravel/membergramui/app/Providers/RouteServiceProvider.php:
$router->model('app-user', 'App\AppUser');

**Comment by rebootcode** [comment]
Open  below file

`
/Applications/MAMP/htdocs/laravel/membergramui/app/Providers/RouteServiceProvider.php
`
and add below code :- 

`
$router->model('app-user', 'App\AppUser');
`

When solved, you may close this issue.
