### ISSUE TITLE
run php artisan nvd:crud

### ISSUE THREAD

**Issue by cupertinobr** [engrnvd/laravel-crud-generator#2]
When I try to run this bellow:

`run php artisan nvd:crud concursos`

returns:

> [Illuminate\Database\QueryException]
>   SQLSTATE[HY000]: General error: 1 near "show": syntax error (SQL: show fields from concursos)

This is my environment
**Laravel Framework version 5.2.14**
**Database: sqlite**
**Mac OS X**

How to fix this?

**Comment by engrnvd** [comment]
Hi @rodolfolsilva, unfortunately sqlite is not currently supported by NVD CRUD generator. However, table fields are fetched by a [function](https://github.com/engrnvd/laravel-crud-generator/blob/master/src/Db.php#L13) which can be edited to support sqlite or any other database system [supported by Laravel](https://laravel.com/docs/5.2/database#introduction). Please feel free to contribute. :)
