### ISSUE TITLE
Select option has no "key" => "value" option ?

### ISSUE THREAD

**Issue by rebootcode** [engrnvd/laravel-crud-generator#8]
Sometimes there are key "1" , and value as "Active". There is no option to do it ?

**Comment by rebootcode** [comment]
Please merge this PR https://github.com/engrnvd/laravel-crud-generator/pull/4 It is important to have "key", "value" pair for select.

**Comment by Necko1996** [comment]
When we  can expect "key" => "value" fix ??
I try to make it but it crash and only show me (field status) that is active....
If it work tell me who to fix this:
{!! \Nvd\Crud\Form::select('status',[1 => 'Da', 2 => 'Ne'], $teren->status)->model($teren)->label("Aktivan")->show() !!}

**Comment by rebootcode** [comment]
Use :- 

`LaravelCollective` Select form element for the purpose.
